agents/urls.py
from django.urls import path
from .views import *

app_name = 'agents'
urlpatterns = [
    path('', AgentList.as_view(), name='agents'),
    path('create/', AgentCreate.as_view(), name='agent_create'),
    path('detail/<pk>/', AgentDetail.as_view(), name='agent_detail'),
    path('delete/<pk>/', AgentDelete.as_view(), name='agent_delete'),
    path('update/<pk>/', AgentUpdate.as_view(), name='agent_update')
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPage, SignUp
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('', LandingPage.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete', PasswordResetCompleteView.as_view(), name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    is_organizer = models.BooleanField(default=False)
    is_agent = models.BooleanField(default=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey(
        'Agent', on_delete=models.SET_NULL, null=True, blank=True)
    organization = models.ForeignKey(
        'UserProfile', on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(
        'Category', related_name='leads', blank=True,  null=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f'{self.first_name}'


class Agent(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    organization = models.ForeignKey(
        'UserProfile', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'
            


class Category(models.Model):
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(
        'UserProfile',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


def post_user_create_signal(sender, instance, created, **kwargs):
    if created:
        if instance.is_organizer:
            UserProfile.objects.create(user=instance)
            print('New user is created :0')


post_save.connect(post_user_create_signal, sender=User)

agents/forms.py
from django import forms
from leads.models import Agent, User


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','username', 'first_name', 'last_name')

agents/views.py
from django.shortcuts import render, redirect, reverse
from .mixins import OraniserandLoginRequiredMixin
from django.views import generic
from leads.models import Agent
from .forms import *
from random import randint
from django.core.mail import send_mail
from django.template import loader
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings





class AgentList(OraniserandLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        queryset = Agent.objects.filter(
            organization=self.request.user.userprofile
        )
        return queryset


class AgentCreate(OraniserandLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agents')

    def get_success_url(self):
        return reverse('agents:agents')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password(str(randint(0, 2000000)))
        current_site = get_current_site(self.request)
        html_message = loader.render_to_string('mail/email.html',{
                'domain': current_site.domain,
                'user': user,
                'protocol': 'https'
        })
        send_mail(
            from_email=settings.FROM_EMAIL,
            subject='You are invited to be an agent',
            recipient_list=[user.email],
            html_message=html_message,
            fail_silently=False,
            message=None
        )
        user.save()
        Agent.objects.create(
            user=user,
            organization=self.request.user.userprofile
        )
        print('------------------------------------------------------------------------------')
        return super(AgentCreate, self).form_valid(form)


class AgentDetail(OraniserandLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = 'agent'

    def get_queryset(self):
        queryset = Agent.objects.filter(
            organization=self.request.user.userprofile
        )
        return queryset


class AgentDelete(OraniserandLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = 'agent'

    def get_success_url(self):
        return reverse('agents:agents')

    def get_queryset(self):
        queryset = Agent.objects.filter(
            organization=self.request.user.userprofile
        )
        return queryset


class AgentUpdate(OraniserandLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    context_object_name = 'agent'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agents')

    def get_queryset(self):
        queryset = Agent.objects.filter(
            organization=self.request.user.userprofile
        )
        return queryset

templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}



{% block content %}
<div class="max-w-lg mx-auto">
  <div class="mt-5 border-b border-gray-200 py-5">
    <a class='hover:text-blue-500' href="{% url 'agents:agents' %}">Go back to agents</a>
</div>
  <h1 class="text-3xl text-gray-500 mb-3">Create a new agent</h1>
      <form method='post' >
        {% csrf_token %}
        {{ form|crispy}}
        <button class="rounded-md text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2" type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mx-auto">
    <div class="mt-5 border-b border-gray-200 py-5">
        <a class='hover:text-blue-500' href="{% url 'agents:agents' %}">Go back to agents</a>
    </div>
    <h1 class="text-3xl text-gray-700 mb-3">Are you Sure You want to delete this agent ?</h1>
    <form method='post' >
        {% csrf_token %}
        {{form|crispy}}
        <button class="rounded-md text-white w-full bg-red-500 hover:bg-red-600 px-3 py-2" type="submit">Delete</button>
    </form>
</div>
{% endblock content %}

templates/agents/agent_detail.html
{% extends "base.html" %}



{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
          <div class="flex mb-4">
              <a href="{% url 'agents:agent_detail' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                  Overview
              </a>
              <a href="{% url 'agents:agent_update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                  Update Details
              </a>    
          </div>
          <div class="flex border-t border-gray-300 py-2">
              <span class="text-gray-500">Full Name</span>
              <span class="ml-auto text-gray-900">{{ agent.user.first_name }} {{ agent.user.last_name }}</span>
          </div>
          <div class="flex border-t border-gray-300 py-2">
              <span class="text-gray-500">Email</span>
              <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
          </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/agents/agent_list.html
{% extends "base.html" %}



{% block content %}


<section class="text-gray-600 body-font">
  <div class="container px-5 py-15 mx-auto flex flex-wrap">

      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
          <h1 class="text-4xl text-gray-800">Agents</h1>
        </div>
        <div>
          <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent_create'  %}">Create a new agent</a>
        </div>
      </div>
      

        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
          <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
              <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Last Name</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">EMAIL</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Leads</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"></th>
              </tr>
            </thead>
            <tbody>
              {% for agent in object_list  %}
                <tr>
                    <td class="border-t-2 border-gray-200 px-4 py-3">
                      <a href="{% url 'agents:agent_detail' pk=agent.pk  %}">
                      {{ agent.user.first_name }}
                      </a>
                    </td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">{{ agent.user.last_name }}</td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">{{ agent.user.email }}</td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">
                    {% if agent.lead_set.count > 0 %}
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                        {{ agent.lead_set.count }}
                    </span>
                    {% else %}
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-400 text-gray-800">
                            zero
                        </span>
                    {% endif %}
                  </td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">
                    <a href="{% url 'agents:agent_update' agent.pk %}" class="text-indigo-600 hover:text-indigo-900">
                      Edit
                    </a>
                  </td>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>


      </div>
    </div>
  </section>
{% endblock content %}

templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block title %}
    {{ lead.first_name }} Update
{% endblock title %}
    
{% block content %}  
<section class="text-gray-700 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
              <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
              <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
              <div class="flex mb-4">
                <a  href="{% url 'agents:agent_detail' pk=agent.pk  %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                <a href="{% url 'agents:agent_update' pk=agent.pk  %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update Details</a>
              </div>
              <form method='post' >
                  {% csrf_token %}
                  {{ form|crispy}}
                  <button class="rounded-md text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2" type="submit">Save</button>
              </form>
              <div class="py-5 border-t border-gray-500">
                <a href="{% url 'agents:agent_delete' pk=agent.pk  %}"
                class="w-1/2 text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">
                  Delete
                </a>
              </div>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
          </div>
        </div>

{% endblock  %}