djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPage, SignUp
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('', LandingPage.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete', PasswordResetCompleteView.as_view(), name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import *

app_name = 'leads'

urlpatterns = [
    path('', LeadList.as_view(), name='leads'),
    path('<int:pk>/', LeadDetail.as_view(), name='lead_detail'),
    
    path('create/', LeadCreate.as_view(), name='lead_create'),
    path('assign-agent/<int:pk>/', AssignAgentView.as_view(), name='assign_agent'),
    path('lead_category_update/<int:pk>/', LeadCategoryUpdate.as_view(), name='lead_category_update'),
    path('update/<int:pk>', LeadUpdate.as_view(), name='lead_update'),
    path('delete/<int:pk>', LeadDelete.as_view(), name='lead_delete'),

    path('categories/', CategoryList.as_view(), name='category_list'),
    path('categories/<pk>/', CategoryDetail.as_view(), name='category_detail'),
    path('categories/<pk>/', CategoryUpdate.as_view(), name='category_update'),
    path('categories/<pk>/', CategoryDelete.as_view(), name='category_delete'),
    path('categories/create/', CategoryCreate.as_view(), name='category_create')
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    is_organizer = models.BooleanField(default=False)
    is_agent = models.BooleanField(default=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey(
        'Agent', on_delete=models.SET_NULL, null=True, blank=True)
    organization = models.ForeignKey(
        'UserProfile', on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(
        'Category', related_name='leads', blank=True,  null=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f'{self.first_name}'


class Agent(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    organization = models.ForeignKey(
        'UserProfile', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'
            


class Category(models.Model):
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(
        'UserProfile',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


def post_user_create_signal(sender, instance, created, **kwargs):
    if created:
        if instance.is_organizer:
            UserProfile.objects.create(user=instance)
            print('New user is created :0')


post_save.connect(post_user_create_signal, sender=User)

leads/forms.py
from django import forms
from .models import Lead, User, Agent
from django.contrib.auth.forms import UsernameField, UserCreationForm, UsernameField
from django.contrib.auth import get_user_model


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
            'description',
            'phone_number',
            'email',
        )


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField()


class CustomUserCreatingForm(UserCreationForm):
    class Meta:
        model = User
        fields = {'username'}
        fields_classes = {
            'username': UsernameField
        }


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )

leads/views.py
from django.db.models import query
from djcrm import settings
from django.views.generic import (
    TemplateView,
    CreateView,
    UpdateView,
    ListView,
    CreateView,
    FormView
)

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from .models import Lead, Agent, Category
from .forms import LeadModelForm, LeadCategoryUpdateForm, CustomUserCreatingForm, AssignAgentForm
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OraniserandLoginRequiredMixin

class LandingPage(TemplateView):
    template_name = 'djcrm/landing.html'


class LeadList(LoginRequiredMixin, ListView):
    template_name = "leads/leads.html"
    context_object_name = 'leads'

    def get_queryset(self):
        queryset = Lead.objects.all()
        # checking if the current logged in user is an organiser
        if self.request.user.is_organizer:
            queryset = queryset.filter(
                organization=self.request.user.userprofile, agent__isnull=False)
        else:
            queryset = queryset.filter(
                agent__user=self.request.user, agent__isnull=False)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadList, self).get_context_data(**kwargs)
        if self.request.user.is_organizer:
            queryset = Lead.objects.filter(
                organization=self.request.user.userprofile, agent__isnull=True)

            context.update({
                'unassigned_leads': queryset
            })
        return context

class LeadDetail(LoginRequiredMixin, DetailView):
    template_name = 'leads/lead_detail.html'

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset


    context_object_name = 'lead'

class LeadUpdate(OraniserandLoginRequiredMixin, UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadModelForm
    context_object_name = 'lead'

    def get_queryset(self):
        queryset = Lead.objects.all()
        # checking if the current logged in user is an organiser
        queryset = queryset.filter(
            organization=self.request.user.userprofile)
        return queryset

    def get_success_url(self):
        return reverse('leads:leads')

class LeadDelete(OraniserandLoginRequiredMixin, DeleteView):
    template_name = "leads/lead_delete.html"

    def get_queryset(self):
        queryset = Lead.objects.all()
        # checking if the current logged in user is an organiser
        queryset = queryset.filter(
            organization=self.request.user.userprofile)
        return queryset

    def get_success_url(self):
        return reverse('leads:leads')

class LeadCreate(OraniserandLoginRequiredMixin, CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:leads')

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile
        lead.save()
        # send_mail(
        #     subject=f'New Lead is created',
        #     recipient_list=[],
        #     message=f"Go the site and the new lead"
        # )
        return super(LeadCreate, self).form_valid(form)

class SignUp(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreatingForm

    def get_success_url(self):
        return reverse('leads:leads')

class AssignAgentView(OraniserandLoginRequiredMixin, FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:leads")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

class CategoryList(LoginRequiredMixin, ListView):
    template_name = "leads/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryList, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile
            )
            context.update({
                "unassigned_lead_count": Lead.objects.filter(organization=user.userprofile, category__isnull=True).count()
            })
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization
            )
        return context

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization
            )
        return queryset

class CategoryDetail(LoginRequiredMixin, DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = 'category'

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization
            )
        return queryset

class LeadCategoryUpdate(LoginRequiredMixin, UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset
    
    def get_success_url(self) -> str:
        return reverse('leads:leads')

class CategoryUpdate(OraniserandLoginRequiredMixin, ListView):
    template_name = "leads/category_update.html"

class CategoryDelete(OraniserandLoginRequiredMixin, ListView):
    template_name = "leads/category_delete.html"

class CategoryCreate(OraniserandLoginRequiredMixin, ListView):
    template_name = "leads/category_create.html"

templates/leads/category_create.html
{% extends "base.html" %}

{% block title %}
  Creating category
{% endblock title %}

{% block content %}  

    <!-- <h1>Lead Create</h1> -->
    <form method='post' >
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Submit</button>
    </form>


{% endblock  %}

templates/leads/category_detail.html
{% extends "base.html" %}

{% block title %}
  Leads ({{ leads|length  }})
{% endblock title %}

<!-- background-color: #007FFF; color:#f0ffff -->
{% block content %}  
<section  class="text-gray-600 body-font">
    <div class="container px-5 py-20 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name  }}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
          Those are the leads of this category
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
              <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all  %}
              <tr>
                <td class="border-t-2 border-gray-200 px-4 py-3">
                    <a href="{% url 'leads:lead_detail' pk=lead.pk %}">
                        {{ lead.first_name }}
                    </a>
                </td>
                <td class="border-t-2 border-gray-200 px-4 py-3">{{ lead.last_name }}</td>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
        <a class="text-blue-500 inline-flex items-center md:mb-2 lg:mb-0">Learn More
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
        <button class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded">Button</button>
      </div> -->
    </div>
  </section>
{% endblock content %}

templates/leads/category_list.html
{% extends "base.html" %}

{% block title %}
  Leads ({{ leads|length  }})
{% endblock title %}

<!-- background-color: #007FFF; color:#f0ffff -->
{% block content %}  
<section  class="text-gray-600 body-font">

    <div class="container px-5 py-20 mx-auto">
      
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
          Those categories segment the leads
        </p>
      </div>

      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Leads count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="border-t-2 border-gray-200 px-4 py-3">Unassigned</td>
              <td class="border-t-2 border-gray-200 px-4 py-3">{{ unassigned_lead_count  }}</td>
              </td>
            </tr>
            {% for category in category_list  %}
              <tr>
               
                  <td class="border-t-2 border-gray-200 px-4 py-3">
                    <a href="{% url 'leads:category_detail' pk=category.pk  %}">
                    {{ category.name }}
                    </a>
                    
                  </td>
          

                <td class="border-t-2 border-gray-200 px-4 py-3">TODO count</td>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block title %}
    {{ lead.first_name }} Update
{% endblock title %}
    
{% block content %}  
<section class="text-gray-700 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
              <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
              <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name  }} {{ lead.last_name  }}</h1>
              <div class="flex mb-4">
                <a href="{% url 'leads:lead_detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'leads:lead_category_update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Category
                </a>
                {% if request.user.is_organizer %}
                <a href="{% url 'leads:lead_update' pk=lead.pk  %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update details</a>
                {% endif %}
            </div>
              <form method='post' >
                  {% csrf_token %}
                  {{ form|crispy}}              

              <div class="flex justify-right">
                    <button type="submit"  class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Save</button>
              </div>
            </form>
            </div>
          </div>
        </div>

{% endblock  %}

templates/leads/lead_detail.html
{% extends "base.html" %}

{% block title %}
  {{ lead.first_name }}'s detail
{% endblock title %}

{% block content %}  
<section class="text-gray-700 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name  }} {{ lead.last_name  }}</h1>
            <div class="flex mb-4">
              <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
             
              <a href="{% url 'leads:lead_category_update' pk=lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
              
              {% if request.user.is_organizer %}
              <a href="{% url 'leads:lead_update' pk=lead.pk  %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update details</a>
              {% endif %}
            </div>
            <p class="leading-relaxed mb-4">{{ lead.description }}</p>
            <div class="flex border-t border-gray-300 py-2">
              <span class="text-gray-500">Age</span>
              <span class="ml-auto text-gray-900">{{ lead.age }}</span>
          </div>
          <div class="flex border-t border-gray-300 py-2">
              <span class="text-gray-500">Email</span>
              <span class="ml-auto text-gray-900">{{ lead.email }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-300 py-2">
              <span class="text-gray-500">Phone Number</span>
              <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
          </div>
            <!-- <div class="flex">
              <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
              <button  class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                </svg>
              </button>
            </div> -->
          </div>
        </div>
      </div>
{% endblock  %}

templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block title %}
    {{ lead.first_name }} Update
{% endblock title %}
    
{% block content %}  
<section class="text-gray-700 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
              <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
              <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name  }} {{ lead.last_name  }}</h1>
              <div class="flex mb-4">
                <a  href="{% url 'leads:lead_detail' pk=lead.pk  %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                <a href="{% url 'leads:lead_category_update' pk=lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
                <a href="{% url 'leads:lead_update' pk=lead.pk  %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update details</a>
              </div>
              <form method='post' >
                  {% csrf_token %}
                  {{ form|crispy}}
                  <button class="rounded-md text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2" type="submit">Save</button>
              </form>
              <div class="py-5 border-t border-gray-500">
                <a href="{% url 'leads:lead_delete' pk=lead.pk  %}"
                class="w-1/2 text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">
                  Delete
                </a>
              </div>
            </div>
          </div>
        </div>

{% endblock  %}

templates/leads/leads.html
{% extends "base.html" %}

{% block title %}
  Leads ({{ leads|length  }})
{% endblock title %}

 
{% block content %}

  <section class="text-gray-600 body-font">
    <div class="container px-5 py-15 mx-auto flex flex-wrap">

      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
          <h1 class="text-4xl text-gray-800">Leads</h1>
          <div>

            <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category_list'  %}">Categories</a>
          </div>
        </div>
        <div>
          {% if request.user.is_organizer %}
            <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead_create'  %}">Create a new lead</a>
          {% endif %}
        </div>
      </div>




      <!--  -->
     
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
          <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
              <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Last Name</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Age</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">EMAIL</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">CELL PHONE</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">CATEGORY</th>
                {% if request.user.is_organizer %}
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"></th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
              {% for lead in leads  %}
                <tr>
                    <td class="border-t-2 border-gray-200 px-4 py-3">
                      <a href="{% url 'leads:lead_detail' pk=lead.pk  %}">
                      {{ lead.first_name }}
                      </a>
                    </td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">{{ lead.last_name }}</td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">{{ lead.age }}</td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">{{ lead.email }}</td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">{{ lead.phone_number }}</td>
                  <td class="border-t-2 border-gray-200 px-4 py-3">
                    {% if lead.category %}
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                        {{ lead.category.name }}
                    </span>
                    {% else %}
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                            Unassigned
                        </span>
                    {% endif %}
                  </td>
                  {% if request.user.is_organizer %}
                  <td class="border-t-2 border-gray-200 px-4 py-3">
                    <a href="{% url 'leads:lead_update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                      Edit
                    </a>
                  </td>
                  {% endif   %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>



        <div class="flex flex-wrap -m-4">
        <!-- unassign leads -->
        {% if unassigned_leads|length > 0 %}
        <div class="flex flex-wrap -m-4">
          <div class="p-4 w-full">
            <h1 class='text-4xl text-gray-800'>Unassigned leads</h1>
          </div>
            {% for lead in unassigned_leads  %}         
            <div class="p-4 lg:w-1/2 md:w-full">
              <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <div class="flex-grow">
                  <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ lead.first_name }} {{ lead.last_name }}</h2>
                  <p class="leading-relaxed text-base">{{ lead.description  }}</p>
                  <a href="{% url 'leads:assign_agent' pk=lead.pk  %}" class="mt-3 text-indigo-500 inline-flex items-center">
                    Assign Agent
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        {% endif %}
        </div>
  </section>
{% endblock content %}